version: '3'
services:
  docker-portal:
    build: .
    args:
      - MONGO_SERVER="mongo.docker-portal.net"
    ports:
      - "7000:7000"
    networks:
      docker-portal-net:
        aliases:
          - web.docker-portal.net

  portal-mongo:
    image: "mongo:3.0"
    networks:
      docker-portal-net:
        aliases:
          - mongo.docker-portal.net
    volumes:
      - dportal-mongo-data:/data/db
      - dportal-mongo-config:/data/configdb

networks:
  docker-portal-net:

volumes:
  dportal-mongo-data:
  dportal-mongo-config: